// Download helpers + C header formatter.

export function toCHeader(name: string, data: Uint8Array): string {
  const ident = name.replace(/[^A-Za-z0-9_]/g, "_");
  const lines: string[] = [];
  lines.push(`// Generated by deskpet animator — DPAK v1 pack "${name}"`);
  lines.push(`#pragma once`);
  lines.push(``);
  lines.push(`const unsigned int ${ident}_dpak_len = ${data.length};`);
  lines.push(`const unsigned char ${ident}_dpak[] = {`);
  for (let i = 0; i < data.length; i += 12) {
    const row = Array.from(data.subarray(i, i + 12))
      .map((b) => "0x" + b.toString(16).padStart(2, "0"))
      .join(", ");
    lines.push(`  ${row},`);
  }
  lines.push(`};`);
  lines.push(``);
  return lines.join("\n");
}

export function downloadBlob(filename: string, data: Uint8Array | string, mime: string): void {
  const blob =
    typeof data === "string"
      ? new Blob([data], { type: mime })
      : new Blob([data.buffer as ArrayBuffer], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}
