// DPAK v1 writer — assembles packs per docs/architecture/asset-format-dpak.md.
import { crc32 } from "./crc32.mjs";
import { fnv1a } from "./fnv.mjs";
import { lz4CompressBlock } from "./lz4.mjs";

export const TYPE = { SPRITE: 1, ANIM: 2, EXPR: 3, FONT: 4, SOUND: 5, PALETTE: 6 };
export const FMT = { RGB565: 0, RGB565_A1: 1, RGB565_A8: 2, PAL8: 3, PAL4: 4 };
export const COMP = { NONE: 0, LZ4_BLOCK: 1, RLE: 2 };
export const LOOP = { once: 0, loop: 1, pingpong: 2 };

// planes: Buffer of the concatenated pixel planes (uncompressed).
// compression: COMP.NONE | COMP.LZ4_BLOCK
export function spriteBlob({ width, height, format, compression = COMP.LZ4_BLOCK, paletteRef = 0, anchorX = 0, anchorY = 0, planes }) {
  const rawSize = planes.length;
  const payload = compression === COMP.LZ4_BLOCK ? lz4CompressBlock(planes) : planes;
  const h = Buffer.alloc(16);
  h.writeUInt16LE(width, 0);
  h.writeUInt16LE(height, 2);
  h.writeUInt8(format, 4);
  h.writeUInt8(compression, 5);
  h.writeUInt16LE(paletteRef, 6);
  h.writeInt16LE(anchorX, 8);
  h.writeInt16LE(anchorY, 10);
  h.writeUInt32LE(rawSize, 12);
  return Buffer.concat([h, payload]);
}

// frames: [{spriteId, durationMs, dx=0, dy=0}]
export function animBlob({ frames, loopMode = LOOP.loop, defaultFpsX10 = 0 }) {
  const b = Buffer.alloc(8 + frames.length * 12);
  b.writeUInt16LE(frames.length, 0);
  b.writeUInt8(loopMode, 2);
  b.writeUInt16LE(defaultFpsX10, 4);
  let o = 8;
  for (const f of frames) {
    b.writeUInt32LE(f.spriteId, o);
    b.writeUInt16LE(f.durationMs, o + 4);
    b.writeInt16LE(f.dx ?? 0, o + 6);
    b.writeInt16LE(f.dy ?? 0, o + 8);
    o += 12;
  }
  return b;
}

// tracks: [{paramId, keys: [{tMs, value, easing=0}]}]
export function exprBlob({ tracks }) {
  const parts = [Buffer.from([tracks.length, 0, 0, 0])];
  for (const t of tracks) {
    const th = Buffer.alloc(4);
    th.writeUInt8(t.paramId, 0);
    th.writeUInt8(t.keys.length, 1);
    parts.push(th);
    for (const k of t.keys) {
      const kb = Buffer.alloc(6);
      kb.writeUInt16LE(k.tMs, 0);
      kb.writeInt16LE(k.value, 2);
      kb.writeUInt8(k.easing ?? 0, 4);
      parts.push(kb);
    }
  }
  return Buffer.concat(parts);
}

// colors: array of RGB565 u16 values (entry 0 reserved as transparent for PAL sprites)
export function paletteBlob({ colors }) {
  const b = Buffer.alloc(4 + colors.length * 2);
  b.writeUInt16LE(colors.length, 0);
  for (let i = 0; i < colors.length; i++) b.writeUInt16LE(colors[i], 4 + i * 2);
  return b;
}

// assets: [{id, type, name, blob}] — id must be unique (encoder assigns 1-based).
export function buildPack({ packId = 0n, assets }) {
  const headerSize = 32;
  const tocSize = assets.length * 32;
  let blobOff = headerSize + tocSize;
  const toc = Buffer.alloc(tocSize);
  const blobs = [];
  assets.forEach((a, i) => {
    const o = i * 32;
    toc.writeUInt32LE(a.id, o);
    toc.writeUInt8(a.type, o + 4);
    toc.writeUInt32LE(fnv1a(a.name), o + 8);
    toc.writeUInt32LE(blobOff, o + 12);
    toc.writeUInt32LE(a.blob.length, o + 16);
    blobs.push(a.blob);
    blobOff += a.blob.length;
  });
  const body = Buffer.concat([toc, ...blobs]);
  const h = Buffer.alloc(headerSize);
  h.write("DPAK", 0, "ascii");
  h.writeUInt16LE(1, 4); // version
  h.writeUInt16LE(0, 6); // flags
  h.writeUInt16LE(assets.length, 8);
  h.writeUInt32LE(32, 12); // tocOffset
  h.writeUInt32LE(crc32(body), 16);
  h.writeBigUInt64LE(BigInt(packId), 20);
  return Buffer.concat([h, body]);
}

export function rgb888to565(r, g, b) {
  return ((r & 0xf8) << 8) | ((g & 0xfc) << 3) | (b >> 3);
}

// Emit a C header with the pack bytes as an array plus named constants.
export function emitCHeader({ pack, arrayName = "g_dpak", guard = "DPAK_EMBED_H", constants = {} }) {
  const lines = [];
  lines.push(`// Generated by dpak-cli — do not edit.`);
  lines.push(`#ifndef ${guard}`);
  lines.push(`#define ${guard}`);
  lines.push(`#include <stdint.h>`);
  lines.push(``);
  for (const [k, v] of Object.entries(constants)) {
    lines.push(`#define ${k} ${typeof v === "bigint" ? `0x${v.toString(16).toUpperCase()}ULL` : `0x${(v >>> 0).toString(16).toUpperCase()}u`}`);
  }
  lines.push(``);
  lines.push(`static const uint32_t ${arrayName}_len = ${pack.length}u;`);
  lines.push(`static const uint8_t ${arrayName}[${pack.length}] = {`);
  for (let i = 0; i < pack.length; i += 16) {
    const row = [];
    for (let j = i; j < Math.min(i + 16, pack.length); j++) row.push(`0x${pack[j].toString(16).padStart(2, "0")}`);
    lines.push(`  ${row.join(",")},`);
  }
  lines.push(`};`);
  lines.push(`#endif // ${guard}`);
  lines.push(``);
  return lines.join("\n");
}
