// Host-side (pio test -e native) unit tests for the DPAK v1 decoder,
// run against the golden fixture generated by tools/dpak-cli/gen-fixtures.mjs.
#include <stdlib.h>
#include <string.h>
#include <unity.h>

#include "dpak.h"
#include "fixtures_golden.h"

static dpak_t pak;

void setUp(void) {
  TEST_ASSERT_EQUAL_INT(DPAK_OK, dpak_open(g_golden, g_golden_len, 0, &pak));
}
void tearDown(void) {}

static void test_header_fields(void) {
  TEST_ASSERT_EQUAL_UINT16(GOLDEN_TOC_COUNT, pak.tocCount);
  TEST_ASSERT_EQUAL_UINT32(32, pak.tocOffset);
  TEST_ASSERT_TRUE(pak.packId == GOLDEN_PACKID); // (avoid UINT64 assert: not enabled in all Unity configs)
}

static void test_bad_magic(void) {
  uint8_t* buf = malloc(g_golden_len);
  memcpy(buf, g_golden, g_golden_len);
  buf[0] = 'X';
  dpak_t p;
  TEST_ASSERT_EQUAL_INT(DPAK_ERR_MAGIC, dpak_open(buf, g_golden_len, 0, &p));
  free(buf);
}

static void test_bad_version(void) {
  uint8_t* buf = malloc(g_golden_len);
  memcpy(buf, g_golden, g_golden_len);
  buf[4] = 2;
  dpak_t p;
  TEST_ASSERT_EQUAL_INT(DPAK_ERR_VERSION, dpak_open(buf, g_golden_len, 0, &p));
  free(buf);
}

static void test_crc_detects_corruption(void) {
  uint8_t* buf = malloc(g_golden_len);
  memcpy(buf, g_golden, g_golden_len);
  buf[g_golden_len / 2] ^= 0xff;
  dpak_t p;
  TEST_ASSERT_EQUAL_INT(DPAK_ERR_CRC, dpak_open(buf, g_golden_len, 0, &p));
  TEST_ASSERT_EQUAL_INT(DPAK_OK, dpak_open(buf, g_golden_len, DPAK_OPEN_SKIP_CRC, &p));
  free(buf);
}

static void test_truncated_pack(void) {
  dpak_t p;
  TEST_ASSERT_EQUAL_INT(DPAK_ERR_BOUNDS, dpak_open(g_golden, 16, 0, &p));
  // header ok but TOC cut off (skip CRC since body is truncated)
  TEST_ASSERT_EQUAL_INT(DPAK_ERR_BOUNDS, dpak_open(g_golden, 40, DPAK_OPEN_SKIP_CRC, &p));
}

static void test_fnv1a_matches_encoder(void) {
  TEST_ASSERT_EQUAL_UINT32(GOLDEN_GRAD32_HASH, dpak_fnv1a_str("grad32"));
  TEST_ASSERT_EQUAL_UINT32(GOLDEN_ANIM_HASH, dpak_fnv1a_str("spin"));
  TEST_ASSERT_EQUAL_UINT32(GOLDEN_EXPR_HASH, dpak_fnv1a_str("blink"));
}

static void test_find_and_get(void) {
  dpak_entry_t e;
  TEST_ASSERT_EQUAL_INT(DPAK_OK, dpak_find(&pak, GOLDEN_GRAD32_HASH, &e));
  TEST_ASSERT_EQUAL_UINT8(DPAK_TYPE_SPRITE, e.type);
  TEST_ASSERT_EQUAL_INT(DPAK_OK, dpak_get(&pak, e.assetId, &e));
  TEST_ASSERT_EQUAL_UINT32(GOLDEN_GRAD32_HASH, e.nameHash);
  TEST_ASSERT_EQUAL_INT(DPAK_ERR_NOTFOUND, dpak_find(&pak, 0xdeadbeef, &e));
  TEST_ASSERT_EQUAL_INT(DPAK_ERR_NOTFOUND, dpak_get(&pak, 999, &e));
}

static void decode_and_check(uint32_t hash, uint32_t rawSize, uint32_t fnv) {
  dpak_entry_t e;
  TEST_ASSERT_EQUAL_INT(DPAK_OK, dpak_find(&pak, hash, &e));
  uint8_t* dst = malloc(rawSize);
  int32_t n = dpak_sprite_decode(&pak, &e, dst, rawSize);
  TEST_ASSERT_EQUAL_INT32((int32_t)rawSize, n);
  TEST_ASSERT_EQUAL_UINT32(fnv, dpak_fnv1a(dst, rawSize));
  free(dst);
}

static void test_decode_grad32_lz4_rgb565(void) {
  decode_and_check(GOLDEN_GRAD32_HASH, GOLDEN_GRAD32_RAWSIZE, GOLDEN_GRAD32_FNV);
}
static void test_decode_circle32_lz4_a1(void) {
  decode_and_check(GOLDEN_CIRCLE32_HASH, GOLDEN_CIRCLE32_RAWSIZE, GOLDEN_CIRCLE32_FNV);
}
static void test_decode_checker32_none_pal8(void) {
  decode_and_check(GOLDEN_CHECKER32_HASH, GOLDEN_CHECKER32_RAWSIZE, GOLDEN_CHECKER32_FNV);
}

static void test_decode_overflow(void) {
  dpak_entry_t e;
  TEST_ASSERT_EQUAL_INT(DPAK_OK, dpak_find(&pak, GOLDEN_GRAD32_HASH, &e));
  uint8_t small[16];
  TEST_ASSERT_EQUAL_INT32(DPAK_ERR_OVERFLOW, dpak_sprite_decode(&pak, &e, small, sizeof(small)));
}

static void test_decode_wrong_type(void) {
  dpak_entry_t e;
  TEST_ASSERT_EQUAL_INT(DPAK_OK, dpak_find(&pak, GOLDEN_ANIM_HASH, &e));
  uint8_t buf[64];
  TEST_ASSERT_EQUAL_INT32(DPAK_ERR_UNSUPPORTED, dpak_sprite_decode(&pak, &e, buf, sizeof(buf)));
}

static void test_palette_and_blit_pal8(void) {
  const uint8_t* palette;
  uint16_t count;
  TEST_ASSERT_EQUAL_INT(DPAK_OK, dpak_palette_get(&pak, 1, &palette, &count));
  TEST_ASSERT_EQUAL_UINT16(4, count);

  dpak_entry_t e;
  TEST_ASSERT_EQUAL_INT(DPAK_OK, dpak_find(&pak, GOLDEN_CHECKER32_HASH, &e));
  dpak_sprite_t s;
  TEST_ASSERT_EQUAL_INT(DPAK_OK, dpak_sprite_header(&pak, &e, &s));
  uint8_t* payload = malloc(s.rawSize);
  TEST_ASSERT_EQUAL_INT32((int32_t)s.rawSize, dpak_sprite_decode(&pak, &e, payload, s.rawSize));

  uint16_t dst[32 * 32];
  for (int i = 0; i < 32 * 32; i++) dst[i] = 0x1234;  // background "key"
  TEST_ASSERT_EQUAL_INT(DPAK_OK, dpak_blit_to_rgb565(&s, payload, palette, count, dst, 32));
  // checker index at (0,0) is 1 -> palette[1] = 0xF800 (red)
  TEST_ASSERT_EQUAL_UINT16(0xF800, dst[0]);
  // cell (8..15, 0..7) has index 2 -> 0x07E0 (green)
  TEST_ASSERT_EQUAL_UINT16(0x07E0, dst[8]);
  free(payload);
}

static void test_blit_a1_skips_transparent(void) {
  dpak_entry_t e;
  TEST_ASSERT_EQUAL_INT(DPAK_OK, dpak_find(&pak, GOLDEN_CIRCLE32_HASH, &e));
  dpak_sprite_t s;
  TEST_ASSERT_EQUAL_INT(DPAK_OK, dpak_sprite_header(&pak, &e, &s));
  uint8_t* payload = malloc(s.rawSize);
  TEST_ASSERT_EQUAL_INT32((int32_t)s.rawSize, dpak_sprite_decode(&pak, &e, payload, s.rawSize));

  uint16_t dst[32 * 32];
  for (int i = 0; i < 32 * 32; i++) dst[i] = 0x1234;
  TEST_ASSERT_EQUAL_INT(DPAK_OK, dpak_blit_to_rgb565(&s, payload, NULL, 0, dst, 32));
  TEST_ASSERT_EQUAL_UINT16(0x1234, dst[0]);            // corner: outside circle, untouched
  TEST_ASSERT_EQUAL_UINT16(0xFD20, dst[16 * 32 + 16]); // center: orange
  free(payload);
}

static void test_anim_blob(void) {
  dpak_entry_t e;
  TEST_ASSERT_EQUAL_INT(DPAK_OK, dpak_find(&pak, GOLDEN_ANIM_HASH, &e));
  TEST_ASSERT_EQUAL_UINT8(DPAK_TYPE_ANIM, e.type);
  TEST_ASSERT_EQUAL_UINT16(3, (uint16_t)(e.blob[0] | (e.blob[1] << 8)));  // frameCount
  TEST_ASSERT_EQUAL_UINT8(1, e.blob[2]);                                  // loopMode LOOP
  // frame 0 spriteId = 2 (grad32)
  TEST_ASSERT_EQUAL_UINT32(2, (uint32_t)(e.blob[8] | (e.blob[9] << 8)));
}

int main(void) {
  UNITY_BEGIN();
  RUN_TEST(test_header_fields);
  RUN_TEST(test_bad_magic);
  RUN_TEST(test_bad_version);
  RUN_TEST(test_crc_detects_corruption);
  RUN_TEST(test_truncated_pack);
  RUN_TEST(test_fnv1a_matches_encoder);
  RUN_TEST(test_find_and_get);
  RUN_TEST(test_decode_grad32_lz4_rgb565);
  RUN_TEST(test_decode_circle32_lz4_a1);
  RUN_TEST(test_decode_checker32_none_pal8);
  RUN_TEST(test_decode_overflow);
  RUN_TEST(test_decode_wrong_type);
  RUN_TEST(test_palette_and_blit_pal8);
  RUN_TEST(test_blit_a1_skips_transparent);
  RUN_TEST(test_anim_blob);
  return UNITY_END();
}
